version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
